image: node:18

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - npm install
    - npm run build
    - mv build public  # GitLab Pages expects files in 'public' folder
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
